### ISSUE TITLE
Wah re choray

### ISSUE THREAD

**Issue by talhabalaj** [mudasirhayat/hello-r#1]

**Comment by mudasirhayat** [comment]
bsdk bs sekh rha tha sara k kese link krte R studio se github ko phir
change ke k push kia

**Comment by talhabalaj** [comment]
@mudasirhayat  wah wah, isay hi lage raho

**Comment by talhabalaj** [comment]
Tu email se reply kr rhaa lol

**Comment by mudasirhayat** [comment]
hn bsdk har jagah mun maro

**Comment by talhabalaj** [comment]
mar mu mar mar
